---

- name: Copy restore dotfiles script
  copy:
    src: roles/dotfiles/files/restore_dotfiles.sh
    dest: "/home/{{ username }}/restore_dotfiles.sh"
    backup: yes
    mode: 777

- name: Running restore dotfiles script
  shell: "/home/{{ username }}/restore_dotfiles.sh"
  become: yes
  become_user: "{{ username }}"

