---

- name: Clone bare dotfiles repo
  git:
    repo: "{{ dotfiles_git_repo }}"
    dest: "/home/{{ username }}"
    separate_git_dir: "/home/{{ username }}/.config/dotfiles.git"
    force: yes

- name: Don't show untracked files on git status
  become: yes
  become_user: "{{ username }}"
  shell: "/usr/bin/git --git-dir=$HOME/.config/dotfiles.git --work-tree=$HOME config --local status.showUntrackedFiles no"

