---

- name: Copy lightdm global config file
  copy:
    src: roles/services/files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    backup: yes

- name: Copy lightdm greeter config file
  copy:
    src: roles/services/files/slick-greeter.conf
    dest: /etc/lightdm/slick-greeter.conf
    backup: yes


- name: Enable lightdm service
  systemd:
    name: lightdm
    enabled: yes
