---

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default('/home/amit/.oh-my-zsh/custom') }}/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default('/home/amit/.oh-my-zsh/custom') }}/plugins/zsh-syntax-highlighting"

- name: Install zsh-forgit
  git:
    repo: https://github.com/wfxr/forgit.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default('/home/amit/.oh-my-zsh/custom') }}/plugins/forgit"
