---

- name: Copy lightdm global config file
  copy:
    src: roles/services/files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    backup: yes

- name: Enable lightdm service
  systemd:
    name: lightdm
    enabled: yes

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes

- name: Enable redshift service
  systemd:
    name: redshift
    scope: global
    enabled: yes
