---

- name: creating google-drive folder in home directory
  shell: mkdir google-drive
  args:
    chdir: ${HOME}

- name: Authenticating with google
  shell: grive
  args:
    chdir: ${HOME}/google-drive

- name: Scheduling syncs on file change events
  shell: |
    systemctl --user enable grive-timer@$(systemd-escape google-drive).timer &&
    systemctl --user start grive-timer@$(systemd-escape google-drive).timer &&
    systemctl --user enable grive-changes@$(systemd-escape google-drive).service &&
    systemctl --user start grive-changes@$(systemd-escape google-drive).service

