---

- name: Create the regular user in wheel group and generate ssh key
  user:
    name: amit
    password: password
    groups: wheel,docker
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Allow users in wheel group to run sudo commands
  lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: Change shell to Zsh
  shell: chsh -s $(which zsh)
  become: yes
  become_user: amit

