---
- hosts: 127.0.0.1
  connection: local
  vars:
    username: "{{ username }}"
    dotfiles_git_repo: "{{ dotfiles_git_repo }}"
  roles:
    - user
    - dotfiles
    - packages
    - plugins
    - services
    - wallpaper
