---

- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: "username"
      prompt: "Enter user name"
  tasks:
    - set_fact: username={{ username }}
      no_log: true

- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: "password"
      prompt: "Enter user password"
  tasks:
    - set_fact: password={{ password }}
      no_log: true

- hosts: 127.0.0.1
  connection: local
  roles:
    - wireless
    - packages
    - user
    - services
    - dotfiles
    - plugins
    - cleanup

